"""Qué mide cada bloque usado por los estilos y a qué familia funcional pertenece.

Las descripciones se basan en el nombre del bloque en el catálogo de SQX y en sus parámetros; cuando
el significado exacto no es verificable sin SQX se indica "(deducido)".
"""

BLOCK_INFO = {
    # --- ruptura de nivel
    "BarOpensAboveHighestAfterOpenBelow": ("ruptura", "La vela abre por encima del máximo de N velas tras abrir por debajo (ruptura Donchian confirmada en apertura)."),
    "BarOpensAboveLowestAfterOpenBelow": ("ruptura", "Abre por encima del mínimo de N velas tras abrir por debajo: recuperación tras una falsa ruptura bajista."),
    "BBBarOpensAboveUpAfterOpenBelow": ("ruptura", "Cruce de apertura por encima de la banda superior de Bollinger."),
    "BBBarClosesAboveUp": ("ruptura", "Cierre por encima de la banda superior de Bollinger."),
    "KCBarOpensAboveUpperAfterOpenBelow": ("ruptura", "Cruce de apertura por encima de la banda superior de Keltner (ATR)."),
    "KCBarClosesAboveUpper": ("ruptura", "Cierre por encima de la banda superior de Keltner."),
    "IchimokuKumoBreakoutBullish": ("ruptura", "El precio sale por encima de la nube de Ichimoku."),
    # --- reversión
    "BBBarOpensAboveDownAfterOpenBelow": ("sobreventa", "Reentrada por encima de la banda inferior de Bollinger tras abrir por debajo."),
    "BBBarClosesBelowDown": ("sobreventa", "Cierre por debajo de la banda inferior de Bollinger (exceso bajista)."),
    "KCBarOpensAboveLowerAfterOpenBelow": ("sobreventa", "Reentrada por encima de la banda inferior de Keltner."),
    "KCBarClosesBelowLower": ("sobreventa", "Cierre por debajo de la banda inferior de Keltner."),
    "RSICrossUp": ("oscilador", "RSI cruza hacia arriba un nivel."),
    "RSILower": ("sobreventa", "RSI por debajo de un nivel."),
    "RSIHigher": ("momentum", "RSI por encima de un nivel (fuerza relativa)."),
    "StochSlowDCrossUp": ("sobreventa", "%D lento del estocástico cruza al alza un nivel."),
    "StochFastKCrossUp": ("sobreventa", "%K rápido del estocástico cruza al alza un nivel."),
    "WPRCrossUp": ("sobreventa", "Williams %R cruza al alza un nivel (escala -100..0)."),
    "CCICrossUp": ("sobreventa", "CCI cruza al alza un nivel."),
    "LaguerreRSICrossUP": ("oscilador", "RSI de Laguerre (0-1, poco retardo) cruza al alza un nivel."),
    "DEMCrossUp": ("sobreventa", "DeMarker (0-1) cruza al alza un nivel."),
    # --- régimen
    "ADXLower": ("regimen_lateral", "ADX por debajo de un nivel: tendencia débil."),
    "ADXFalling": ("regimen_lateral", "ADX descendente: la tendencia pierde fuerza."),
    "KERbelowLevel": ("regimen_lateral", "Ratio de eficiencia de Kaufman bajo: movimiento errático, sin dirección."),
    "KERaboveLevel": ("tendencia", "Ratio de eficiencia de Kaufman alto: movimiento direccional limpio."),
    "ADXHigher": ("tendencia", "ADX por encima de un nivel: tendencia con fuerza."),
    "ADXRising": ("tendencia", "ADX creciente: la tendencia gana fuerza."),
    "DICrossUp": ("tendencia", "DI+ cruza por encima de DI- (deducido del nombre)."),
    # --- tendencia
    "MARising": ("tendencia", "Media móvil con pendiente positiva."),
    "MABarClosesAbove": ("tendencia", "Cierre por encima de una media móvil."),
    "LinRegRising": ("tendencia", "Regresión lineal con pendiente positiva."),
    "SuperTrendUPTrend": ("tendencia", "SuperTrend en modo alcista."),
    "BarClosesAboveSuperTrend": ("tendencia", "Cierre por encima de la línea SuperTrend."),
    "IchimokuTenkanKijunCrossBullish": ("tendencia", "Cruce alcista Tenkan/Kijun de Ichimoku."),
    "MACDMainCrossAboveSignal": ("momentum", "MACD cruza por encima de su señal."),
    "MACDMainHigherZero": ("momentum", "MACD por encima de cero (media rápida > lenta): independiente de la escala de precio."),
    "MACDMainCrossAboveZero": ("momentum", "MACD cruza cero al alza."),
    "FasterHMAIsAboveSlowerHMA": ("tendencia", "Media de Hull rápida por encima de la lenta."),
    "FastKAMAAboveSlowKAMA": ("tendencia", "KAMA rápida por encima de la lenta (media adaptativa)."),
    "KAMARising": ("tendencia", "KAMA con pendiente positiva."),
    "AroonCrossesAbove": ("tendencia", "Aroon Up cruza por encima de Aroon Down (deducido del nombre)."),
    "VortexUptrend": ("tendencia", "Indicador Vortex en tendencia alcista."),
    "GannHiLoUPTrend": ("tendencia", "Gann HiLo activador en modo alcista."),
    "PSARBarLower": ("tendencia", "Parabolic SAR por debajo de la vela (deducido: régimen alcista)."),
    "ROCAboveLevel": ("momentum", "Rate of Change (%) por encima de un nivel: momentum de series temporales."),
    "ROCRising": ("momentum", "ROC creciente."),
    # --- volatilidad
    "ATRRising": ("volatilidad", "ATR creciente: expansión de volatilidad (sin nivel absoluto)."),
    "ATRChangesUp": ("volatilidad", "El ATR cambia de dirección al alza."),
    "StdDevRising": ("volatilidad", "Desviación típica creciente."),
    "BBUpperRising": ("volatilidad", "Banda superior de Bollinger subiendo (expansión)."),
    # --- velas / estructura
    "BullishEngulfing": ("vela", "Envolvente alcista."),
    "Hammer": ("vela", "Martillo (rechazo de mínimos)."),
    "PiercingLine": ("vela", "Pauta penetrante alcista."),
    "Doji": ("vela", "Doji (indecisión; útil sólo en contexto)."),
    "IsBullishFractal": ("vela", "Fractal alcista de Williams (mínimo local confirmado)."),
    # --- tiempo
    "BarHourIs": ("tiempo", "La vela es de una hora concreta."),
    "BarHourIsBigger": ("tiempo", "Hora de la vela posterior a H."),
    "BarHourIsSmaller": ("tiempo", "Hora de la vela anterior a H."),
    "BarDayOfWeekIs": ("tiempo", "Día de la semana concreto."),
    # --- indicadores (valores para comparar)
    "Indicators.Highest": ("nivel", "Máximo de N velas (canal Donchian)."),
    "Indicators.Lowest": ("nivel", "Mínimo de N velas."),
    "Indicators.HighestInRange": ("nivel", "Máximo entre dos horas del día (rango horario, p. ej. asiático)."),
    "Indicators.LowestInRange": ("nivel", "Mínimo entre dos horas del día."),
    "Indicators.ATR": ("volatilidad", "ATR: rango medio verdadero."),
    "Indicators.TrueRange": ("volatilidad", "Rango verdadero de la vela."),
    "Indicators.EMA": ("tendencia", "Media exponencial."),
    "Indicators.SMA": ("tendencia", "Media simple."),
    "Indicators.KAMA": ("tendencia", "Media adaptativa de Kaufman."),
    "Indicators.HullMovingAverage": ("tendencia", "Media de Hull."),
    "Indicators.SuperTrend": ("tendencia", "Línea SuperTrend."),
    "Indicators.BollingerBands": ("nivel", "Bandas de Bollinger (media ± k·desviación)."),
    "Indicators.KeltnerChannel": ("nivel", "Canal de Keltner (media ± k·ATR)."),
    "Indicators.RSI": ("sobreventa", "RSI (valor)."),
    "Indicators.Stochastic": ("sobreventa", "Estocástico (valor)."),
    "Indicators.WilliamsPR": ("sobreventa", "Williams %R (valor)."),
    "Indicators.CCI": ("sobreventa", "CCI (valor)."),
    "Indicators.Fractal": ("nivel", "Último fractal (máximo/mínimo local)."),
    "Prices.Close": ("precio", "Cierre."), "Prices.Open": ("precio", "Apertura."),
    "Prices.High": ("precio", "Máximo."), "Prices.Low": ("precio", "Mínimo."),
    "Prices.HighD": ("nivel", "Máximo del día anterior."), "Prices.LowD": ("nivel", "Mínimo del día anterior."),
    "Prices.OpenD": ("nivel", "Apertura diaria."), "Prices.CloseD": ("nivel", "Cierre del día anterior."),
    "Prices.HighW": ("nivel", "Máximo semanal."), "Prices.LowW": ("nivel", "Mínimo semanal."),
    "Prices.CloseW": ("nivel", "Cierre semanal."), "Prices.HighM": ("nivel", "Máximo mensual."),
    "Prices.LowM": ("nivel", "Mínimo mensual."),
    "Prices.SessionHigh": ("nivel", "Máximo de una sesión horaria configurable."),
    "Prices.SessionLow": ("nivel", "Mínimo de una sesión horaria configurable."),
    "Prices.SessionOpen": ("nivel", "Apertura de una sesión horaria configurable."),
    "Prices.HeikenAshiOpen": ("precio", "Apertura Heikin-Ashi (vela suavizada)."),
    "Prices.HeikenAshiClose": ("precio", "Cierre Heikin-Ashi."),
    "Prices.HeikenAshiHigh": ("precio", "Máximo Heikin-Ashi."),
    "Prices.HeikenAshiLow": ("precio", "Mínimo Heikin-Ashi."),
    # --- comparadores
    "IsGreater": ("comparador", "A > B."), "IsLower": ("comparador", "A < B."),
    "CrossesAbove": ("comparador", "A cruza B al alza."), "CrossesBelow": ("comparador", "A cruza B a la baja."),
    "IsGreaterCount": ("comparador", "A > B durante N velas seguidas."),
    "IsLowerCount": ("comparador", "A < B durante N velas seguidas."),
    "IsRising": ("comparador", "A sube durante N velas."), "IsFalling": ("comparador", "A baja durante N velas."),
    # --- niveles de órdenes stop/limit
    "Stop/Limit Price Levels.Highest": ("orden_nivel", "Precio de la orden = máximo de N velas."),
    "Stop/Limit Price Levels.Lowest": ("orden_nivel", "Precio de la orden = mínimo de N velas."),
    "Stop/Limit Price Levels.High": ("orden_nivel", "Precio de la orden = máximo de una vela (vela señal)."),
    "Stop/Limit Price Levels.Low": ("orden_nivel", "Precio de la orden = mínimo de una vela."),
    "Stop/Limit Price Levels.HighestInRange": ("orden_nivel", "Precio = máximo de un rango horario."),
    "Stop/Limit Price Levels.SessionHigh": ("orden_nivel", "Precio = máximo de sesión."),
    "Stop/Limit Price Levels.HighD": ("orden_nivel", "Precio = máximo del día anterior."),
    "Stop/Limit Price Levels.OpenD": ("orden_nivel", "Precio = apertura diaria."),
    "Stop/Limit Price Levels.HighW": ("orden_nivel", "Precio = máximo semanal."),
    "Stop/Limit Price Levels.HighM": ("orden_nivel", "Precio = máximo mensual."),
    "Stop/Limit Price Levels.BollingerBands": ("orden_nivel", "Precio = banda de Bollinger."),
    "Stop/Limit Price Levels.KeltnerChannel": ("orden_nivel", "Precio = banda de Keltner."),
    "Stop/Limit Price Levels.SMA": ("orden_nivel", "Precio = media simple."),
    "Stop/Limit Price Levels.EMA": ("orden_nivel", "Precio = media exponencial."),
    "Stop/Limit Price Levels.SuperTrend": ("orden_nivel", "Precio = línea SuperTrend."),
    "Stop/Limit Price Levels.Fractal": ("orden_nivel", "Precio = último fractal."),
    "Stop/Limit Price Ranges.ATR": ("orden_offset", "Desplazamiento del precio de la orden = k·ATR."),
    "Stop/Limit Price Ranges.BarRange": ("orden_offset", "Desplazamiento = k·rango de la vela."),
    "Stop/Limit Price Ranges.BBRange": ("orden_offset", "Desplazamiento = k·anchura de Bollinger."),
    "Stop/Limit Price Ranges.SmallestRange": ("orden_offset", "Desplazamiento = k·rango mínimo de N velas (contracción)."),
    "Stop/Limit Price Ranges.TrueRange": ("orden_offset", "Desplazamiento = k·rango verdadero."),
}

FAMILY_LABEL = {
    "ruptura": "Ruptura de nivel", "sobreventa": "Reversión / sobreventa", "oscilador": "Oscilador",
    "momentum": "Momentum", "regimen_lateral": "Régimen lateral", "tendencia": "Tendencia",
    "volatilidad": "Volatilidad", "vela": "Patrón de vela", "tiempo": "Tiempo", "nivel": "Nivel de referencia",
    "precio": "Precio", "comparador": "Comparador", "orden_nivel": "Precio de orden stop/limit",
    "orden_offset": "Desplazamiento de orden",
}
